### ISSUE TITLE
Make needs to be run BEFORE make userspace-base/full to generate Jinx

### ISSUE THREAD

**Issue by CoolSoulz** [NSG650/Polaris#30]
**Describe the bug**
If running make userspace-base/full BEFORE make like the guide on the README suggests, it'll fail as it cant find Jinx. The solution is to run make to download Jinx and set it to be executable for some reason

**To Reproduce**
1. Follow the guide and run make userspace-base/full
2. See error

**Expected behavior**
I expected it to work and get Jinx

**Screenshots**
None

**Environment (please complete the following information):**
 - Host OS: Microsoft Windblows
 - Host OS Version: 11 IoT Enterprise LTSC 24H2
 - Emulator/Hypervisor: Not installed yet
 - Emulator/Hypervisor None as not installed yet

**Additional context**
None

**Comment by NSG650** [comment]
Known issue. Will update the README.

**Comment by CoolSoulz** [comment]
okay
